<?php

namespace Adress\AdressBundle\Repository;

/**
 * coordinatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coordinatesRepository extends \Doctrine\ORM\EntityRepository
{
}
