<?php

namespace Adress\AdressBundle\Repository;

/**
 * StreetTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
