vendor_connect_users:
    resource: "@VendorConnectUsersBundle/Resources/config/routing.yml"
    prefix:   /


admin_users:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    host: admin.teamroquette.tk
    prefix:   /
