core_core:
    host:  "www.mealandbox.fr"
    resource: "@CoreCoreBundle/Resources/config/routing.yml"
    prefix:   /


vendor_connect_users:
    resource: "@VendorConnectUsersBundle/Resources/config/routing.yml"
    prefix:   /compte
admin_admin:
  host:  "admin.mealandbox.fr"
  resource: "@AdminAdminBundle/Resources/config/routing.yml"
  prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /connect

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix:   /connect

# hwi_oauth_login:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix:   /login
