core_core:
    host:  "www.mealandbox.fr"
    resource: "@CoreCoreBundle/Resources/config/routing.yml"
    prefix:   /

vendor_connect_users:
    resource: "@VendorConnectUsersBundle/Resources/config/routing.yml"
    prefix:   /compte
admin_admin:
  host:  "admin.mealandbox.fr"
  resource: "@AdminAdminBundle/Resources/config/routing.yml"
  prefix:   /
