# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Vendor\ConnectUsersBundle\Entity\UsersWeb:
            algorithm: sha512
            iterations: 6666
            encode_as_base64: true
        Vendor\ConnectUsersBundle\Entity\UsersEmployee:
            algorithm: sha512
            iterations: 6666
            encode_as_base64: true
                    
    role_hierarchy:
            ROLE_USER: [ROLE_USER]
            ROLE_LIVREUR: [ROLE_LIVREUR]
            ROLE_ADMIN: [ROLE_ADMIN]
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        core:
            entity:
                    class:    Vendor\ConnectUsersBundle\Entity\UsersWeb
                    property: email
        admin:
            entity:
                    class:    Vendor\ConnectUsersBundle\Entity\UsersEmployee
                    property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/compte/connexion/$
            security: false   
        core:
            host: ^www\.mealandbox\.fr$
            pattern: ^/
            anonymous: true
            provider:  core
            form_login:
               login_path: /login
               check_path: /compte/connexion/connexionweb
               default_target_path: /
               failure_path: /login
            logout:
                path:   /compte/deconnexion
                target: /
                success_handler: timeout

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                httponly: true
        
        admin:
            host: ^admin\.mealandbox\.fr$
            pattern: ^/*
            anonymous: true
            provider:  admin
            form_login:
               login_path: /login
               check_path: /compte/connexion/connexionadmin
               default_target_path: /
               failure_path: /login
            logout:
                path:   /compte/deconnexion
                target: /
    access_control:
               - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: ^admin\.mealandbox\.fr$  }            
              # - { path: ^/*, roles: ROLE_ADMIN, host: ^admin\.mealandbox\.fr$ }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html