# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Vendor\ConnectUsersBundle\Entity\Users: plaintext
        #Vendor\ConnectUsersBundle\Entity\Users: plaintext


    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity:
                    class:    Vendor\ConnectUsersBundle\Entity\Users
                    property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            

        main:
            anonymous: true
            pattern:   ^/
            provider:  main
            form_login:
               login_path: /compte/connexion
               check_path: /compte/login_check
               default_target_path: /contact
               failure_path: /
            logout:
                path:   /compte/deconnexion
                target: /


    access_control:
               - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
               - { path: ^/Commande, roles: ROLE_USERS }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
