# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    Validedate:  
         class: Vendor\ConnectUsersBundle\Validator\Constraints\Date
         properties:
           birthdate:
            - NotBlank: ~

    Sitemap:
        class : Core\CoreBundle\Service\Sitemap\SiteMap
        arguments: ["@router","@doctrine.orm.entity_manager"]