admin_homepage:
    path:    /
    defaults: { _controller: AdminAdminBundle:Core:index }

admin_utilisateurs:
    path:    /users/{page}
    defaults: { _controller: AdminAdminBundle:UsersEmployee:index }

admin_utilisateurs_add:
    path:    /users/add/
    defaults: { _controller: AdminAdminBundle:UsersEmployee:addUsers }

admin_utilisateurs_edit:
    path:    /users/edit/{email}
    defaults: { _controller: AdminAdminBundle:UsersEmployee:editUsers }

admin_utilisateurs_delete:
    path:    /users/delete/{email}
    defaults: { _controller: AdminAdminBundle:UsersEmployee:deleteUsers }

admin_produits:
    path:    /product/{page}
    defaults: { _controller: AdminAdminBundle:Product:index }

admin_produits_add:
    path:    /product/{page}
    defaults: { _controller: AdminAdminBundle:Product:index }

admin_produits_edit:
    path:    /product/delete/{id}
    defaults: { _controller: AdminAdminBundle:Product:index }

admin_produits_delete:
    path:    /product/delete/{id}
    defaults: { _controller: AdminAdminBundle:Product:index }

admin_menu:
    path:    /menu
    defaults: { _controller: AdminAdminBundle:Core:menu }

admin_vehicules:
    path:    /vehicules
    defaults: { _controller: AdminAdminBundle:Core:vehicules }

admin_relais:
    path:    /relais
    defaults: { _controller: AdminAdminBundle:Core:relais }