admin_homepage:
    path:    /
    defaults: { _controller: AdminAdminBundle:Core:index }

admin_comptecurrentusers:
    path:    /profile
    defaults: { _controller: AdminAdminBundle:Core:compte }

# --------------------Users-------------------- #
admin_utilisateurs:
    path:    /users
    defaults: { _controller: AdminAdminBundle:UsersEmployee:index}

admin_utilisateurs_add:
    path:    /users/add
    defaults: { _controller: AdminAdminBundle:UsersEmployee:add }

admin_utilisateurs_edit:
    path:    /users/edit/{email}
    defaults: { _controller: AdminAdminBundle:UsersEmployee:edit }
    options:
        expose: true

admin_utilisateurs_delete:
    path:    /users/delete/{email}
    defaults: { _controller: AdminAdminBundle:UsersEmployee:delete }
    options:
        expose: true

admin_utilisateurs_filter:
    path:    /users/{page}/{nbMaxParPage}/{champ}/{order}
    defaults: { _controller: AdminAdminBundle:UsersEmployee:orderBy}
    options:
        expose: true

admin_utilisateurs_search:
    path:    /users/search
    defaults: { _controller: AdminAdminBundle:UsersEmployee:search}
    options:
        expose: true

# --------------------Produit-------------------- #
admin_produits:
    path:    /product
    defaults: { _controller: AdminAdminBundle:Product:index}
   
admin_produits_add:
    path:    /product/add
    defaults: { _controller: AdminAdminBundle:Product:addProduct }

admin_produits_edit:
    path:    /product/edit/{id}
    defaults: { _controller: AdminAdminBundle:Product:editProduct }

admin_produits_delete:
    path:    /product/delete/{id}
    defaults: { _controller: AdminAdminBundle:Product:deleteProduct }

# --------------------Categorie-------------------- #
admin_categorie:
    path:    /categorie
    defaults: { _controller: AdminAdminBundle:Categorie:index }
   
admin_categorie_add:
    path:    /categorie/add
    defaults: { _controller: AdminAdminBundle:Categorie:addCategorie }

admin_categorie_edit:
    path:    /categorie/edit/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:editCategorie }

admin_categorie_delete:
    path:    /categorie/delete/{id}
    defaults: { _controller: AdminAdminBundle:Categorie:deleteCategorie }



# --------------------Fournisseurs-------------------- #
admin_fournisseurs:
    path:    /provider
    defaults: { _controller: AdminAdminBundle:Provider:index }
   
admin_fournisseurs_add:
    path:    /provider/add
    defaults: { _controller: AdminAdminBundle:Provider:addProvider }

admin_fournisseurs_edit:
    path:    /provider/edit/{id}
    defaults: { _controller: AdminAdminBundle:Provider:editProvider }

admin_fournisseurs_delete:
    path:    /provider/delete/{id}
    defaults: { _controller: AdminAdminBundle:Provider:deleteProvider }





# --------------------Allergene-------------------- #
admin_allergene:
    path:    /allergene
    defaults: { _controller: AdminAdminBundle:Allergene:index  }
   
admin_allergene_add:
    path:    /allergene/add
    defaults: { _controller: AdminAdminBundle:Allergene:addAllergene }

admin_allergene_edit:
    path:    /allergene/edit/{id}
    defaults: { _controller: AdminAdminBundle:Allergene:editAllergene }

admin_allergene_delete:
    path:    /allergene/delete/{id}
    defaults: { _controller: AdminAdminBundle:Allergene:deleteAllergene }

# --------------------Menu-------------------- #


admin_menu:
    path:    /menu
    defaults: { _controller: AdminAdminBundle:Menu:index }

admin_menu_add:
    path:    /menu/add
    defaults: { _controller: AdminAdminBundle:Menu:addMenu }

admin_menu_edit:
    path:    /menu/edit/{id}
    defaults: { _controller: AdminAdminBundle:Menu:editMenu }

admin_menu_delete:
    path:    /menu/delete/{id}
    defaults: { _controller: AdminAdminBundle:Menu:deleteMenu }

# --------------------Vehicule-------------------- #
admin_vehicules:
    path:    /vehicules
    defaults: { _controller: AdminAdminBundle:Core:vehicules }


# --------------------Relais-------------------- #
admin_relais:
    path:    /relais
    defaults: { _controller: AdminAdminBundle:Relais:index }

admin_relais_add:
    path:    /relais/add
    defaults: { _controller: AdminAdminBundle:Relais:addRelais }

