#home
homepage:
    path:     /
    defaults: { _controller: CoreCoreBundle:Core:accueil }
#cgv
cgvpage:
    path:     /conditions-generales-de-vente
    defaults: { _controller: CoreCoreBundle:Core:cgv }
#mension
mentionspage:
    path:     /mentions-legales
    defaults: { _controller: CoreCoreBundle:Core:mentions }

#passwordreset
resetpasswordpage:
    path:     /resetpassword/{token}
    defaults: { _controller: CoreCoreBundle:Core:resetPassword }

#relais
relaispage:
    path:     /relais
    defaults: { _controller: CoreCoreBundle:Relais:index }

allrelais:
    path: /relais/all
    defaults: { _controller: CoreCoreBundle:Relais:all}
    options:
            expose: true

#contact
contactpage:
    path:     /contact
    defaults: { _controller: CoreCoreBundle:Contact:contact }
# commande
commandepage:
    path:     /commande
    defaults: { _controller: CoreCoreBundle:Commande:commande }

downloadorder:
    path:     /commande/download/{id}
    defaults: { _controller: CoreCoreBundle:Commande:downloadResumeOrder }
# panier
panierpage:
    path:     /panier
    defaults: { _controller: CoreCoreBundle:Panier:panier }
addproductpage:
    path:     /produits/add/{id}/{quantity}
    defaults: { _controller: CoreCoreBundle:Panier:addProducts }
    options:
        expose: true
historyCommande:
    path:     /commande/historique/{id}
    defaults: { _controller: CoreCoreBundle:Commande:history }

deleteproductpage:
    path:     /produits/delete/{id}
    defaults: { _controller: CoreCoreBundle:Panier:deleteProducts }
    options:
        expose: true
changequantity:
    path:     /produits/quantite/{id}/{quantity}
    defaults: { _controller: CoreCoreBundle:Panier:changeQuantity }
    options:
        expose: true

# produit
productpage:
    path:     /produits
    defaults: { _controller: CoreCoreBundle:Product:products }

productdetailpage:
    path:     /produits/{id}
    defaults: { _controller: CoreCoreBundle:Product:productsDetail }
    options:
        expose: true
        

#filter
productfilterpage:
    path:     /produits/filter/{offsetMin}/{offsetMax}/{priceMin}/{priceMax}/{categorie}/{allergene}
    defaults: { _controller: CoreCoreBundle:Product:productsFilter,allergene:null}
    options:
        expose: true


# actuality
actualitypage:
    path:     /actualites
    defaults: { _controller: CoreCoreBundle:Posts:index }

actualityscrollpage:
    path:     /actualites/{offsetmin}/{offsetmax}
    defaults: { _controller: CoreCoreBundle:Posts:scroll }
    options:
        expose: true

actualitydetailpage:
    path:     /actualites/{id}
    defaults: { _controller: CoreCoreBundle:Posts:detail }
    options:
        expose: true
#login 
loginpage:
    path:     /login
    defaults: { _controller: CoreCoreBundle:Users:login }

#compte 
comptepage:
    path: /compte/user
    defaults: {_controller:CoreCoreBundle:Users:compte}