homepage:
    path:     /
    defaults: { _controller: CoreCoreBundle:Core:accueil }
contactpage:
    path:     /contact
    defaults: { _controller: CoreCoreBundle:Core:contact }
commandepage:
    path:     /commande
    defaults: { _controller: CoreCoreBundle:Core:contact }