services:
#    core_core.example:
#        class: Core\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Sitemap:
        class : Core\CoreBundle\Service\Sitemap\SiteMap
        arguments: ["@router","@doctrine.orm.entity_manager"]
    panier:
        class: Core\CoreBundle\Service\Panier\Panier
        arguments: []
    meta:
        class: Core\CoreBundle\Service\Meta\Meta
        arguments: []
    timeout:
        class: Core\CoreBundle\Service\TimeOut\TimeOut
        arguments: ["@security.http_utils","@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.responses}