services:
#    core_core.example:
#        class: Core\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    panier:
       class: Core\CoreBundle\Service\Panier\Panier
       arguments: []