<?php

namespace Core\CoreBundle\Repository;

/**
 * AddresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddresRepository extends \Doctrine\ORM\EntityRepository
{
}
