<?php

namespace Core\CoreBundle\Repository;

/**
 * AllergeneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergeneRepository extends \Doctrine\ORM\EntityRepository
{
}
