<?php

namespace Core\CoreBundle\Repository;

/**
 * CodePostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePostalRepository extends \Doctrine\ORM\EntityRepository
{
}
