<?php

namespace Core\CoreBundle\Repository;

/**
 * CoordoneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonatesRepository extends \Doctrine\ORM\EntityRepository
{
}
