<?php

namespace Core\CoreBundle\Repository;

/**
 * imagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imagesRepository extends \Doctrine\ORM\EntityRepository
{
}
