<?php

namespace Core\CoreBundle\Repository;

/**
 * OpeningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningRepository extends \Doctrine\ORM\EntityRepository
{
}
