<?php

namespace Core\CoreBundle\Repository;

/**
 * OrderClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderClientRepository extends \Doctrine\ORM\EntityRepository
{
}
