<?php

namespace Core\CoreBundle\Repository;

/**
 * PayementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayementRepository extends \Doctrine\ORM\EntityRepository
{
}
