<?php

namespace Core\CoreBundle\Repository;

/**
 * RelaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelaisRepository extends \Doctrine\ORM\EntityRepository
{


}
