<?php

namespace Core\CoreBundle\Repository;

/**
 * TypeStreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeStreetRepository extends \Doctrine\ORM\EntityRepository
{
}
